import { useEffect, useRef, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ArrowDownRight, ArrowUpRight, BrainCircuit, Check, ChevronDown, Code2, Database, Github, Globe2, Linkedin, Mail, MapPin, Menu, Phone, Server, Terminal, X } from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);
const profileImage = '/images/WhatsApp_Image_2026-09-15_at_19.59.24_(1).jpeg';
const githubUrl = 'https://github.com/mohddawoodkh';
const linkedInUrl = 'https://www.linkedin.com/in/mohammed-dawood-khan-04082b24/';
const emailUrl = 'mailto:mohddawoodkh@gmail.com';
type Project = { number: string; title: string; subtitle: string; description: string; technologies: string[]; features: string[]; architecture?: string[]; problem: string; solution: string };
const projects: Project[] = [
  { number: '01', title: 'AI Chatbot', subtitle: 'Retrieval-Augmented Generation', description: 'Built a RAG chatbot using LangChain and FAISS vector search to deliver context-aware responses over custom datasets.', technologies: ['LangChain', 'FAISS', 'LLMs', 'RAG', 'Python', 'Prompt Engineering'], features: ['Custom dataset ingestion', 'Semantic vector retrieval', 'Context-aware responses', 'Prompt-engineered output'], problem: 'General-purpose models can lose the context of a private or specialised dataset.', solution: 'A retrieval layer finds relevant knowledge first, then supplies it to the language model for grounded answers.', architecture: ['Documents', 'FAISS', 'Retriever', 'LLM', 'Response'] },
  { number: '02', title: 'Multi-Agent Research System', subtitle: 'Autonomous research and critique', description: 'Built a multi-agent research system in Python and LangChain that orchestrates web search, web reading, report writing and automated critique.', technologies: ['Python', 'LangChain', 'Tavily', 'Requests', 'BeautifulSoup', 'OpenAI GPT-4o-mini', 'Streamlit'], features: ['Live web search', 'Web content extraction', 'Multi-agent orchestration', 'Report synthesis', 'Automated critic', 'Verdict generation', 'Streamlit UI', 'CLI and Markdown download'], problem: 'Research is often fragmented across search, reading, synthesis and review steps.', solution: 'Specialised agents collaborate through a clear pipeline, turning a question into a structured, critiqued report.', architecture: ['Search Agent', 'Reader Agent', 'Writer Chain', 'Critic Chain'] },
  { number: '03', title: 'AI Video Assistant', subtitle: 'Multimodal Video Intelligence & RAG System', description: 'An end-to-end video intelligence pipeline for YouTube URLs and local audio/video files.', technologies: ['yt-dlp', 'pydub', 'FFmpeg', 'OpenAI Whisper', 'Sarvam AI', 'LangChain', 'Mistral AI', 'ChromaDB', 'HuggingFace embeddings', 'Streamlit'], features: ['YouTube and local file processing', 'Audio extraction and conversion', 'Chunking and speech-to-text', 'Summarisation', 'Action-item, decision and open-question extraction', 'Transcript RAG Q&A'], problem: 'Important decisions and follow-ups are buried inside long-form audio and video.', solution: 'A multimodal pipeline transforms media into searchable, summarised knowledge with follow-up question answering.', architecture: ['Video / Audio', 'Whisper', 'Chunks', 'Embeddings', 'ChromaDB', 'RAG Q&A'] },
];
const skillGroups = [
  { label: 'Languages', icon: Code2, items: ['Go / Golang', 'Python', 'Java', 'C'] },
  { label: 'Backend & Architecture', icon: Server, items: ['Microservices', 'RESTful APIs', 'Event-Driven Architecture', 'RabbitMQ', 'Message Queuing', 'CI/CD'] },
  { label: 'Databases', icon: Database, items: ['PostgreSQL', 'MongoDB', 'Redis', 'MySQL'] },
  { label: 'AI / ML / GenAI', icon: BrainCircuit, items: ['LLMs', 'RAG', 'LangChain', 'Vector Search', 'FAISS', 'Pinecone', 'Prompt Engineering'] },
  { label: 'Tools & DevOps', icon: Terminal, items: ['Docker', 'Git', 'GitHub', 'Postman', 'Terminal / CLI'] },
  { label: 'Web', icon: Globe2, items: ['React.js', 'JavaScript', 'HTML', 'CSS'] },
];
const navItems = ['About', 'Skills', 'Experience', 'Projects', 'AI', 'Contact'];
function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [selectedProject, setSelectedProject] = useState<Project | null>(null); const appRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const context = gsap.context(() => { const intro = gsap.timeline({ defaults: { ease: 'power3.out' } }); intro.from('.hero-kicker, .hero-title-line, .hero-copy, .hero-actions, .hero-visual', { opacity: 0, y: 28, duration: 0.85, stagger: 0.1 }, 0.15); gsap.utils.toArray<HTMLElement>('.reveal').forEach((element) => { gsap.from(element, { scrollTrigger: { trigger: element, start: 'top 84%', once: true }, opacity: 0, y: 32, duration: 0.8, ease: 'power3.out' }); }); gsap.utils.toArray<HTMLElement>('.timeline-line').forEach((element) => { gsap.from(element, { scrollTrigger: { trigger: element, start: 'top 82%', once: true }, scaleY: 0, transformOrigin: 'top', duration: 1.3, ease: 'power2.out' }); }); }, appRef); return () => context.revert(); }, []);
  const closeMenu = () => setMenuOpen(false);
  return (<div ref={appRef} className="site-shell">
    <header className="site-header"><a className="brand" href="#home" aria-label="Mohammed Dawood Khan home" onClick={closeMenu}><span className="brand-mark">MDK</span><span className="brand-caption">Software / AI</span></a><nav className={menuOpen ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation"><a href="#home" onClick={closeMenu}>Home</a>{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={closeMenu}>{item}</a>)}</nav><div className="header-links"><a href={githubUrl} target="_blank" rel="noreferrer" aria-label="GitHub profile"><Github size={17} /></a><a href={linkedInUrl} target="_blank" rel="noreferrer" aria-label="LinkedIn profile"><Linkedin size={17} /></a></div><button className="menu-toggle" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></header>
    <main>
      <section id="home" className="hero section-pad"><div className="hero-grid"><div className="hero-content"><p className="eyebrow hero-kicker"><span className="eyebrow-dot" /> Available for meaningful work · Bangalore, India</p><h1 className="hero-title" aria-label="Mohammed Dawood Khan"><span className="hero-title-line">Mohammed</span><span className="hero-title-line accent-text">Dawood Khan</span></h1><div className="hero-role hero-copy"><span>Software Developer</span><span>AI / ML</span><span>Generative AI</span><span>Backend Engineering</span></div><p className="hero-description hero-copy">Building scalable software and intelligent AI systems.</p><p className="hero-support hero-copy">Software developer focused on backend engineering, distributed systems, Generative AI, LLM applications and real-world problem solving.</p><div className="hero-actions"><a className="button button-primary" href="#projects">View my work <ArrowDownRight size={17} /></a><a className="button button-ghost" href={emailUrl}>Let&apos;s connect <ArrowUpRight size={17} /></a></div></div><div className="hero-visual"><div className="image-frame"><img src={profileImage} alt="Mohammed Dawood Khan working at a desk" fetchPriority="high" /></div><div className="visual-note visual-note-top"><span>01 / 04</span><span>Engineer in progress</span></div><div className="visual-note visual-note-bottom"><span className="line-dot" /> Backend · AI · Systems</div></div></div><a href="#about" className="scroll-cue" aria-label="Scroll to about"><span>Scroll to explore</span><ArrowDownRight size={16} /></a></section>
      <section id="about" className="section-pad about-section"><div className="section-heading reveal"><p className="eyebrow">01 — Profile</p><h2>Engineering software.<br /><span className="muted-text">Exploring intelligence.</span></h2></div><div className="about-grid"><div className="about-lead reveal"><p className="large-copy">2026 B.Tech Computer Engineering (AI/ML) graduate and backend engineer with hands-on experience building Go microservices, REST APIs and event-driven systems.</p><p>Alongside backend engineering, I build AI applications using LLMs, Retrieval-Augmented Generation, LangChain and vector search. I care about systems that are dependable underneath and intuitive on the surface.</p><a className="text-link" href={linkedInUrl} target="_blank" rel="noreferrer">More about my journey <ArrowUpRight size={16} /></a></div><div className="stats-grid reveal"><div className="stat"><strong>2026</strong><span>B.Tech AI/ML<br />Graduate</span></div><div className="stat"><strong>15+</strong><span>REST API<br />Endpoints</span></div><div className="stat"><strong>5</strong><span>Member<br />Capstone Team</span></div><div className="stat"><strong>Backend<br />+ AI</strong><span>Engineering<br />Focus</span></div></div></div></section>
      <section id="skills" className="section-pad skills-section"><div className="section-heading section-heading-row reveal"><div><p className="eyebrow">02 — Toolkit</p><h2>Tools for the<br /><span className="muted-text">hard problems.</span></h2></div><p className="section-aside">A practical stack for building robust services, clear interfaces and intelligent products.</p></div><div className="skills-grid">{skillGroups.map(({ label, icon: Icon, items }) => <article className="skill-card reveal" key={label}><Icon className="skill-icon" size={21} /><h3>{label}</h3><div className="tag-list">{items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
      <section id="experience" className="section-pad experience-section"><div className="section-heading reveal"><p className="eyebrow">03 — Experience</p><h2>Where ideas meet<br /><span className="muted-text">operational reality.</span></h2></div><div className="timeline reveal"><div className="timeline-line" /><div className="timeline-dot" /><div className="timeline-content"><div className="timeline-meta"><span>Jan 2026 — May 2026</span><span>KaasLabs · Bangalore</span></div><h3>Software Developer Intern <span>— Backend</span></h3><ul>{['Built scalable Go microservices and REST APIs for distributed backend workflows.', 'Engineered asynchronous event-driven workflows with RabbitMQ.', 'Designed data-access workflows across PostgreSQL, MongoDB and Redis.', 'Developed and documented 15+ RESTful API endpoints.', 'Followed GitHub-based CI/CD practices.'].map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><div className="tag-list timeline-tags">{['Go', 'REST APIs', 'RabbitMQ', 'PostgreSQL', 'MongoDB', 'Redis', 'GitHub', 'CI/CD'].map((item) => <span key={item}>{item}</span>)}</div></div></div></section>
      <section id="projects" className="section-pad projects-section"><div className="section-heading section-heading-row reveal"><div><p className="eyebrow">04 — Selected work</p><h2>Built to be<br /><span className="muted-text">useful.</span></h2></div><p className="section-aside">Projects at the intersection of software engineering, language models and practical problem solving.</p></div><div className="projects-list">{projects.map((project) => <button className="project-card reveal" key={project.number} type="button" onClick={() => setSelectedProject(project)}><span className="project-number">{project.number}</span><div className="project-main"><p className="project-subtitle">{project.subtitle}</p><h3>{project.title}</h3><p>{project.description}</p><div className="tag-list">{project.technologies.slice(0, 5).map((item) => <span key={item}>{item}</span>)}</div></div><span className="project-arrow"><ArrowUpRight size={23} /></span></button>)}</div></section>
      <section id="ai" className="section-pad ai-section"><div className="ai-glow" /><div className="section-heading reveal"><p className="eyebrow">05 — Intelligence layer</p><h2>Exploring the<br /><span className="accent-text">intelligence layer.</span></h2><p className="section-intro">I build AI systems that connect models to the right context, tools and workflows.</p></div><div className="ai-content"><div className="ai-capabilities reveal">{['LLMs', 'RAG', 'LangChain', 'Vector Search', 'Multi-Agent Systems', 'Prompt Engineering', 'Speech-to-Text', 'AI Automation'].map((item, index) => <div className="capability" key={item}><span>0{index + 1}</span><strong>{item}</strong><ArrowUpRight size={15} /></div>)}</div><div className="architecture reveal"><p className="eyebrow">A simple mental model</p>{['USER', 'AGENT', 'TOOLS / SEARCH', 'RETRIEVAL', 'LLM', 'RESPONSE'].map((item, index, list) => <div className="arch-node" key={item}><span>{item}</span>{index < list.length - 1 && <ChevronDown size={18} />}</div>)}</div></div></section>
      <section className="section-pad build-section"><div className="section-heading reveal"><p className="eyebrow">06 — Engineering principles</p><h2>How I <span className="accent-text">build.</span></h2></div><div className="build-grid reveal">{['Problem', 'Architecture', 'Implementation', 'Testing', 'Observability', 'Deployment', 'Iteration'].map((item, index) => <div className="build-step" key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div><div className="principles reveal">{['Scalability', 'Clean Architecture', 'API Design', 'Event-Driven Systems', 'Performance', 'Reliability', 'Observability', 'Automation'].map((item) => <span key={item}>{item}</span>)}</div></section>
      <section id="contact" className="section-pad contact-section"><div className="contact-inner reveal"><p className="eyebrow">07 — Contact</p><h2>Let&apos;s build something<br /><span className="accent-text">meaningful.</span></h2><p>Open to opportunities in Software Engineering, Backend Engineering and Generative AI.</p><div className="contact-actions"><a className="button button-primary" href={emailUrl}>Email me <Mail size={17} /></a><a className="button button-ghost" href={linkedInUrl} target="_blank" rel="noreferrer">Connect on LinkedIn <Linkedin size={17} /></a><a className="button button-ghost" href={githubUrl} target="_blank" rel="noreferrer">View GitHub <Github size={17} /></a></div><div className="contact-details"><span><MapPin size={16} /> Bangalore, Karnataka, India</span><a href={emailUrl}><Mail size={16} /> mohddawoodkh@gmail.com</a><a href="tel:+918861892836"><Phone size={16} /> +91 8861892836</a></div></div></section>
    </main>
    <footer className="site-footer"><div><a className="brand" href="#home"><span className="brand-mark">MDK</span></a><p>Built with curiosity, code and AI.</p></div><div className="footer-right"><p>Mohammed Dawood Khan</p><div><a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a><a href={linkedInUrl} target="_blank" rel="noreferrer">LinkedIn</a><a href={emailUrl}>Email</a></div><small>© 2026 Mohammed Dawood Khan</small></div></footer>
    {selectedProject && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><article className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" aria-label="Close project details" onClick={() => setSelectedProject(null)}><X size={20} /></button><p className="eyebrow">Project {selectedProject.number} · Deep dive</p><h2 id="project-title">{selectedProject.title}</h2><p className="modal-subtitle">{selectedProject.subtitle}</p><div className="modal-grid"><div><h3>Overview</h3><p>{selectedProject.description}</p><h3>Problem</h3><p>{selectedProject.problem}</p><h3>Solution</h3><p>{selectedProject.solution}</p></div><div><h3>Architecture</h3><div className="modal-architecture">{selectedProject.architecture?.map((item, index) => <span key={item}>{item}{index < (selectedProject.architecture?.length ?? 0) - 1 && <ChevronDown size={14} />}</span>)}</div><h3>Features</h3><ul className="feature-list">{selectedProject.features.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul></div></div><div className="modal-tech"><h3>Technology</h3><div className="tag-list">{selectedProject.technologies.map((item) => <span key={item}>{item}</span>)}</div></div><div className="modal-footer"><span>GitHub — Coming Soon</span><a href={emailUrl}>Ask about this project <ArrowUpRight size={15} /></a></div></article></div>}
  </div>);
}
export default App;
